name: goreleaser

on:
  push:
    tags:
    - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: '1.23.4'
    - name: Go vendor
      run: go mod vendor
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
        workdir: "./"
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}